FROM python:3.8.4-alpine

RUN apk update \
  && apk add --no-cache bash vim openssh curl git
ENV APP_ROOT /var/www/app

WORKDIR /var/www/app

RUN pip install --upgrade pip \
  && pip install --upgrade setuptools

COPY ./requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt
